apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 8h0m0s
  install:
    createNamespace: true
  targetNamespace: ingress-nginx
  values:
    controller:
      service:
        enabled: true
        type: LoadBalancer
        annotations:
          cloudprovider.harvesterhci.io/ipam: dhcp
          cloudprovider.harvesterhci.io/healthcheck-port: "80"